base:
  font: ./fonts/SourceHanSansCN-Light.otf
  bold_font: ./fonts/SourceHanSansCN-Bold.otf
  #input_dir: ./input
  #output_dir: ./output
  


logo: # true or false, different Artist logo format: Brand+'_'+Artist. i.e. Canon_Alex ./logos/canon_04.13.2421.png
  enable: true
  makes:
    nikon:
      id: NIKON
      path: ./logos/nikon.png
    canon_Alex:
      id: Canon_Alex
      path: ./logos/canon_04.13.2421.png
    canon_ALEX:
      id: Canon_ALEX
      path: ./logos/canon_04.13.2421.png
    canon:
      id: Canon
      path: ./logos/canon.png
    sony:
      id: SONY
      path: ./logos/sony.png
    pentax:
      id: PENTAX
      path: ./logos/pentax.png
    panasonic:
      id: Panasonic
      path: ./logos/panasonic.png
    olympus:
      id: Olympus
      path: ./logos/olympus_blue_gold.png
    fujifilm:
      id: FUJIFILM
      path: ./logos/fujifilm.png
    leica:
      id: leica
      path: ./logos/leica_logo.png
    rioch:
      id: RIOCH
      path: ./logos/ricoh.png
    hasselblad:
      id: HASSELBLAD
      path: ./logos/hasselblad.png

layout: # you can select one type in ['normal'], may more type supports later
  # you can get more information in https://lsvm.xyz/2023/02/semi-utils-intro/
  type: normal
  elements: # the information displayed in the watermark
    # you can select from ['Date', 'Model', 'LensModel', 'Param', 'Make', 'None', 'DateFilename']
    - id: IPTC_Tag
    - id: Model_Lens_Exposureinfo
    - id: Param
    - id: DateFilename

#DO NOT CHANGE ELEMENTS ORDER
#The programme will NOT check the data's order base on the key, so DO FOLLOW the order.
lens_rename:
    'TAMRON SP 17-50mm F/2.8 DiII A16E':
    - rename: 'TAMRON 17-50mm F/2.8 A16'
    - short_name: 'TAMRON 17-50 A016'
    'TAMRON SP 150-600mm F/5-6.3 Di VC USD G2 A022':
    - rename: 'TAMRON 150-600mm F/5-6.3 A022' 
    - short_name: '156 A022'
    'RF800mm F11 IS STM':
    - rename: 'RF800mm F11 IS STM' 
    - short_name: 'RF811'

cameras:
    enable: true
    
    'NIKON D5500':
    - sensor_resolution_X: 5472
    - sensor_resolution_Y: 3648
    - crop: 1.5
    - multi_sensor: 1
    - rename: 'NIKON D5500' 
    - short_name: 'D5500'
    
    'Canon EOS 7D Mark II':
    - sensor_resolution_X: 5472
    - sensor_resolution_Y: 3648
    - crop: 1.6
    - multi_sensor: 1
    - rename: 'EOS 7D Mark II' 
    - short_name: '7D2'
    
    'Canon EOS 80D':
    - sensor_resolution_X: 6000
    - sensor_resolution_Y: 4000
    - crop: 1.6
    - multi_sensor: 1
    - rename: 'EOS 80D'
    - short_name: '80D'

    'Canon EOS 800D':
    - sensor_resolution_X: 6000
    - sensor_resolution_Y: 4000
    - crop: 1.6
    - multi_sensor: 1
    - rename: 'EOS 800D'
    - short_name: '800D'

    
    'Canon EOS 550D':
    - sensor_resolution_X: 5184
    - sensor_resolution_Y: 3456
    - crop: 1.6
    - multi_sensor: 1
    - rename: 'EOS 550D'
    - short_name: '550D'
    
    'NIKON D750':
    - sensor_resolution_X: 6016
    - sensor_resolution_Y: 4016
    - crop: 1.0
    - multi_sensor: 1
    - rename: 'NIKON D750'
    - short_name: 'D750'
    
    'MI 5s':
    - sensor_resolution_X: 4072
    - sensor_resolution_Y: 3176
    - crop: 5.5
    - multi_sensor: 1
    - rename: 'MI 5s'
    - short_name: 'MI 5s'
    
    'ZV-E10':
    - sensor_resolution_X: 6000
    - sensor_resolution_Y: 4000
    - crop: 1.5
    - multi_sensor: 1
    - rename: 'ZV-E10'
    - short_name: 'ZV-E10'
    
    'M2104K10AC':
    - sensor_resolution_X: 0
    - sensor_resolution_Y: 0
    - crop: 0
    #set multi sensor>2 to enable multi_sensor support. the value doesn't matter for now
    #sensor information in this order: FocalLength(with mm after it(important)),full_fram_resolutionX,full_fram_resolutionY. 
    - multi_sensor: 2
    - rename: 'RMNote10Pro'
    - short_name: 'RMNote10Pro'
    #wide: 1.66mm crop11 3280x2464,Digizoom correct 0.6 Don't lose mm in specialFocalLength
    - specialFocalLength--1: 1.66mm
    - sensor_resolution_X--1: 0
    - sensor_resolution_Y--1: 0 
    #main: 4.74mm crop5.4 4624x3472 , Don't lose mm in specialFocalLength
    - specialFocalLength--2: 4.74mm
    - sensor_resolution_X--2: 24969.6
    - sensor_resolution_Y--2: 18748.8 
    #Front: 3.27mm crop8.28 3456x4608 , Don't lose mm in specialFocalLength
    - specialFocalLength--3: 3.27mm
    - sensor_resolution_X--3: 0
    - sensor_resolution_Y--3: 0
    #main: 200mm crop5.4 4624x3472 , Don't lose mm in specialFocalLength
    - specialFocalLength--4: 200mm
    - sensor_resolution_X--4: 0
    - sensor_resolution_Y--4: 0
    
    'Canon EOS 600D':
    - sensor_resolution_X: 5184
    - sensor_resolution_Y: 3456
    - crop: 1.6
    - multi_sensor: 1
    - rename: 'EOS 600D'
    - short_name: '600D'
    
    'Canon EOS R6':
    - sensor_resolution_X: 5472
    - sensor_resolution_Y: 3648
    - crop: 1.0
    - multi_sensor: 1
    - rename: 'EOS R6'
    - short_name: 'EOS R6'
    
    
    'Canon EOS R6m2':
    - sensor_resolution_X: 6000
    - sensor_resolution_Y: 4000
    - crop: 1.0
    - multi_sensor: 1
    - rename: 'EOS R6 Mark II'
    - short_name: 'EOS R62'
    
    'ILCE-7RM3A':
    - sensor_resolution_X: 7952
    - sensor_resolution_Y: 5304
    - crop: 1.0
    - multi_sensor: 1
    - rename: 'A7R3a'
    - short_name: 'A7R3a'
    
    'NIKON Z 6':
    - sensor_resolution_X: 5000
    - sensor_resolution_Y: 3328
    - crop: 1.0
    - multi_sensor: 1
    - rename: 'NIKON Z 6'    
    - short_name: 'NIKON Z 6'    
    
    'Canon EOS R5':
    - sensor_resolution_X: 8192
    - sensor_resolution_Y: 5464
    - crop: 1.0
    - multi_sensor: 1
    - rename: 'EOS R5'
    - short_name: 'EOS R5'
    
    'Unknow':
    - sensor_resolution_X: 0
    - sensor_resolution_Y: 0
    - crop: 1
    - multi_sensor: 1
    - rename: 'Camera_Not_Config'
    - short_name: 'TBD'
